/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3tfavHgZw46Q2spXSS6bmf
// Component: gtgX5FVmB0wH

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: WNoPdp2TUL0b/component

import { useScreenVariants as useScreenVariantsdVrsUiNrcF8D } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: dVRSUiNrcF8d/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 3tfavHgZw46Q2spXSS6bmf/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: gtgX5FVmB0wH/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: TYUtSE6TCJS2/icon
import ChevronDown2Icon from "./icons/PlasmicIcon__ChevronDown2"; // plasmic-import: RD5rGEvsIUbD/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 1Vlq8ZSnmVKV/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: NNu5s9B7Sh4l/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: zYJfS4hU28Sk/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  main?: Flex__<"div">;
  virpayFejlec1?: Flex__<"div">;
  d1Teaser?: Flex__<"div">;
  d111?: Flex__<"div">;
  d121?: Flex__<"div">;
  uTeaser?: Flex__<"div">;
  u1?: Flex__<"div">;
  d2Teaser?: Flex__<"div">;
  d211?: Flex__<"div">;
  d221?: Flex__<"div">;
  d1MTeaser?: Flex__<"div">;
  d1M1?: Flex__<"div">;
  d1Vasarlas?: Flex__<"div">;
  d112?: Flex__<"div">;
  d122?: Flex__<"div">;
  napiMatricaFrame?: Flex__<"div">;
  vasarlas?: Flex__<"div">;
  button?: Flex__<"div">;
  _10NaposMatricaFrame?: Flex__<"div">;
  vasarlas2?: Flex__<"div">;
  button2?: Flex__<"div">;
  haviMatricaFrame?: Flex__<"div">;
  vasarlas3?: Flex__<"div">;
  button3?: Flex__<"div">;
  varmegyeiEvesMatricaFrame?: Flex__<"div">;
  vasarlas4?: Flex__<"div">;
  button4?: Flex__<"div">;
  evesMatricaFrame?: Flex__<"div">;
  vasarlas5?: Flex__<"div">;
  button5?: Flex__<"div">;
  d2Vasarlas?: Flex__<"div">;
  napiMatricaFrame2?: Flex__<"div">;
  vasarlas6?: Flex__<"div">;
  button6?: Flex__<"div">;
  _10NaposMatricaFrame2?: Flex__<"div">;
  vasarlas7?: Flex__<"div">;
  button7?: Flex__<"div">;
  haviMatricaFrame2?: Flex__<"div">;
  vasarlas8?: Flex__<"div">;
  button8?: Flex__<"div">;
  varmegyeiEvesMatricaFrame2?: Flex__<"div">;
  vasarlas9?: Flex__<"div">;
  button9?: Flex__<"div">;
  evesMatricaFrame2?: Flex__<"div">;
  vasarlas10?: Flex__<"div">;
  button10?: Flex__<"div">;
  d212?: Flex__<"div">;
  d222?: Flex__<"div">;
  d1MVasarlas?: Flex__<"div">;
  napiMatricaFrame3?: Flex__<"div">;
  vasarlas11?: Flex__<"div">;
  button11?: Flex__<"div">;
  _10NaposMatricaFrame3?: Flex__<"div">;
  vasarlas12?: Flex__<"div">;
  button12?: Flex__<"div">;
  haviMatricaFrame3?: Flex__<"div">;
  vasarlas13?: Flex__<"div">;
  button13?: Flex__<"div">;
  d1M2?: Flex__<"div">;
  spacer?: Flex__<"div">;
  uVasarlas?: Flex__<"div">;
  napiMatricaFrame4?: Flex__<"div">;
  vasarlas14?: Flex__<"div">;
  button14?: Flex__<"div">;
  _10NaposMatricaFrame4?: Flex__<"div">;
  vasarlas15?: Flex__<"div">;
  button15?: Flex__<"div">;
  haviMatricaFrame4?: Flex__<"div">;
  vasarlas16?: Flex__<"div">;
  button16?: Flex__<"div">;
  varmegyeiEvesMatricaFrame3?: Flex__<"div">;
  vasarlas17?: Flex__<"div">;
  button17?: Flex__<"div">;
  evesMatricaFrame3?: Flex__<"div">;
  vasarlas18?: Flex__<"div">;
  button18?: Flex__<"div">;
  u2?: Flex__<"div">;
  columns?: Flex__<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsdVrsUiNrcF8D()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__esqJh)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___8DEf7)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___42XyR)}
                displayHeight={"40px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"40px"}
                src={{
                  src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgY2xhc3M9Ikljb25fX0ltYWdlLXNjLTF0N2Z2azUtMCBjRlBLZkUiPgogIDxwYXRoIGZpbGw9IiMxNDE4MjQiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTMuMDA1IDNIMTV2MTJIMy4wMDVWM3pNMTQuNSAyMWE2LjUgNi41IDAgMTAwLTEzIDYuNSA2LjUgMCAwMDAgMTN6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__emXkO)}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__i59Tp
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Services"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__meFqv
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Features"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___0AlCx
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Company"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ueEws
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Contact"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__cVcqL
                  )}
                  href={"https://www.plasmic.app/"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToNewPage"] = true
                      ? (() => {
                          const actionArgs = { destination: `/login` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToNewPage"] != null &&
                      typeof $steps["goToNewPage"] === "object" &&
                      typeof $steps["goToNewPage"].then === "function"
                    ) {
                      $steps["goToNewPage"] = await $steps["goToNewPage"];
                    }

                    $steps["updateStateVariable"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;
                            undefined;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateStateVariable"] != null &&
                      typeof $steps["updateStateVariable"] === "object" &&
                      typeof $steps["updateStateVariable"].then === "function"
                    ) {
                      $steps["updateStateVariable"] = await $steps[
                        "updateStateVariable"
                      ];
                    }
                  }}
                  platform={"react"}
                >
                  {"Log in"}
                </PlasmicLink__>
                <Button
                  className={classNames("__wab_instance", sty.button__koykb)}
                  color={"black"}
                  end={
                    <ChevronDown2Icon
                      className={classNames(projectcss.all, sty.svg__hUklS)}
                      role={"img"}
                    />
                  }
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jkbYb
                      )}
                    >
                      {"Sign up"}
                    </div>
                  }
                  start={
                    <CircleIcon
                      className={classNames(projectcss.all, sty.svg__jHbw)}
                      role={"img"}
                    />
                  }
                />
              </Stack__>
            </Stack__>
          </Stack__>
          <div
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            className={classNames(projectcss.all, sty.main)}
          >
            <div
              data-plasmic-name={"virpayFejlec1"}
              data-plasmic-override={overrides.virpayFejlec1}
              className={classNames(projectcss.all, sty.virpayFejlec1)}
            />

            <div
              data-plasmic-name={"d1Teaser"}
              data-plasmic-override={overrides.d1Teaser}
              className={classNames(projectcss.all, sty.d1Teaser)}
            >
              <div
                data-plasmic-name={"d111"}
                data-plasmic-override={overrides.d111}
                className={classNames(projectcss.all, sty.d111)}
              />

              <div
                data-plasmic-name={"d121"}
                data-plasmic-override={overrides.d121}
                className={classNames(projectcss.all, sty.d121)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uJ3X
                )}
              >
                {"D1"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6REvF
                )}
              >
                {
                  "Motorker\u00e9kp\u00e1r, valamint a legfeljebb 3,5 tonna megengedett legnagyobb \u00f6sszt\u00f6meg\u0171, legfeljebb 7 szem\u00e9ly sz\u00e1ll\u00edt\u00e1s\u00e1ra alkalmas szem\u00e9lyg\u00e9pkocsi \u00e9s annak vontatm\u00e1nya."
                }
              </div>
            </div>
            <div
              data-plasmic-name={"uTeaser"}
              data-plasmic-override={overrides.uTeaser}
              className={classNames(projectcss.all, sty.uTeaser)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9KdGs
                )}
              >
                {"U"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u5YOb
                )}
              >
                {
                  "D2 \u00e9s B2 d\u00edjkateg\u00f3ri\u00e1ba tartoz\u00f3 j\u00e1rm\u0171vek vontatm\u00e1nya."
                }
              </div>
              <div
                data-plasmic-name={"u1"}
                data-plasmic-override={overrides.u1}
                className={classNames(projectcss.all, sty.u1)}
              />
            </div>
            <div
              data-plasmic-name={"d2Teaser"}
              data-plasmic-override={overrides.d2Teaser}
              className={classNames(projectcss.all, sty.d2Teaser)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__amFyH
                )}
              >
                {
                  "H\u00e9tn\u00e9l t\u00f6bb szem\u00e9ly sz\u00e1ll\u00edt\u00e1sra alkalmas szem\u00e9lyg\u00e9pkocsi, valamint a legfeljebb 3,5 tonna megengedett legnagyobb \u00f6sszt\u00f6meg\u0171 teherg\u00e9pkocsi \u00e9s lak\u00f3aut\u00f3."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t3Yhw
                )}
              >
                {"D2"}
              </div>
              <div
                data-plasmic-name={"d211"}
                data-plasmic-override={overrides.d211}
                className={classNames(projectcss.all, sty.d211)}
              />

              <div
                data-plasmic-name={"d221"}
                data-plasmic-override={overrides.d221}
                className={classNames(projectcss.all, sty.d221)}
              />
            </div>
            <div
              data-plasmic-name={"d1MTeaser"}
              data-plasmic-override={overrides.d1MTeaser}
              className={classNames(projectcss.all, sty.d1MTeaser)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cLg8W
                )}
              >
                {"Kiz\u00e1r\u00f3lag motorker\u00e9kp\u00e1rokra."}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fhlJz
                )}
              >
                {"D1M"}
              </div>
              <div
                data-plasmic-name={"d1M1"}
                data-plasmic-override={overrides.d1M1}
                className={classNames(projectcss.all, sty.d1M1)}
              />
            </div>
            <div
              data-plasmic-name={"d1Vasarlas"}
              data-plasmic-override={overrides.d1Vasarlas}
              className={classNames(projectcss.all, sty.d1Vasarlas)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tSm5I
                )}
              >
                {
                  "Motorker\u00e9kp\u00e1r, valamint a legfeljebb 3,5 tonna megengedett legnagyobb \u00f6sszt\u00f6meg\u0171, legfeljebb 7 szem\u00e9ly sz\u00e1ll\u00edt\u00e1s\u00e1ra alkalmas szem\u00e9lyg\u00e9pkocsi \u00e9s annak vontatm\u00e1nya."
                }
              </div>
              <div
                data-plasmic-name={"d112"}
                data-plasmic-override={overrides.d112}
                className={classNames(projectcss.all, sty.d112)}
              />

              <div
                data-plasmic-name={"d122"}
                data-plasmic-override={overrides.d122}
                className={classNames(projectcss.all, sty.d122)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__arbkw
                )}
              >
                {"D1"}
              </div>
              <div
                data-plasmic-name={"napiMatricaFrame"}
                data-plasmic-override={overrides.napiMatricaFrame}
                className={classNames(projectcss.all, sty.napiMatricaFrame)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oxrlm
                  )}
                >
                  {"Napi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mUwW6
                  )}
                >
                  {"5320 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas"}
                  data-plasmic-override={overrides.vasarlas}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas)}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"_10NaposMatricaFrame"}
                data-plasmic-override={overrides._10NaposMatricaFrame}
                className={classNames(projectcss.all, sty._10NaposMatricaFrame)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ggUig
                  )}
                >
                  {"10 napos"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gnAn6
                  )}
                >
                  {"6620 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas2"}
                  data-plasmic-override={overrides.vasarlas2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas2)}
                >
                  <div
                    data-plasmic-name={"button2"}
                    data-plasmic-override={overrides.button2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button2
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"haviMatricaFrame"}
                data-plasmic-override={overrides.haviMatricaFrame}
                className={classNames(projectcss.all, sty.haviMatricaFrame)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nnhzF
                  )}
                >
                  {"Havi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g5Ar5
                  )}
                >
                  {"10710 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas3"}
                  data-plasmic-override={overrides.vasarlas3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas3)}
                >
                  <div
                    data-plasmic-name={"button3"}
                    data-plasmic-override={overrides.button3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button3
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"varmegyeiEvesMatricaFrame"}
                data-plasmic-override={overrides.varmegyeiEvesMatricaFrame}
                className={classNames(
                  projectcss.all,
                  sty.varmegyeiEvesMatricaFrame
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zrGu
                  )}
                >
                  {"V\u00e1rmegyei \u00e9ves"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vFaWm
                  )}
                >
                  {"6890 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas4"}
                  data-plasmic-override={overrides.vasarlas4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas4)}
                >
                  <div
                    data-plasmic-name={"button4"}
                    data-plasmic-override={overrides.button4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button4
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"evesMatricaFrame"}
                data-plasmic-override={overrides.evesMatricaFrame}
                className={classNames(projectcss.all, sty.evesMatricaFrame)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eYyf4
                  )}
                >
                  {"V\u00e1rmegyei \u00e9ves"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jEIjK
                  )}
                >
                  {"59210 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas5"}
                  data-plasmic-override={overrides.vasarlas5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas5)}
                >
                  <div
                    data-plasmic-name={"button5"}
                    data-plasmic-override={overrides.button5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button5
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
            </div>
            <div
              data-plasmic-name={"d2Vasarlas"}
              data-plasmic-override={overrides.d2Vasarlas}
              className={classNames(projectcss.all, sty.d2Vasarlas)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zw9W5
                )}
              >
                {
                  "H\u00e9tn\u00e9l t\u00f6bb szem\u00e9ly sz\u00e1ll\u00edt\u00e1sra alkalmas szem\u00e9lyg\u00e9pkocsi, valamint a legfeljebb 3,5 tonna megengedett legnagyobb \u00f6sszt\u00f6meg\u0171 teherg\u00e9pkocsi \u00e9s lak\u00f3aut\u00f3."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tqVj0
                )}
              >
                {"D2"}
              </div>
              <div
                data-plasmic-name={"napiMatricaFrame2"}
                data-plasmic-override={overrides.napiMatricaFrame2}
                className={classNames(projectcss.all, sty.napiMatricaFrame2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t1H
                  )}
                >
                  {"Napi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__watMc
                  )}
                >
                  {"7560 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas6"}
                  data-plasmic-override={overrides.vasarlas6}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas6)}
                >
                  <div
                    data-plasmic-name={"button6"}
                    data-plasmic-override={overrides.button6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button6
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"_10NaposMatricaFrame2"}
                data-plasmic-override={overrides._10NaposMatricaFrame2}
                className={classNames(
                  projectcss.all,
                  sty._10NaposMatricaFrame2
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pdHZl
                  )}
                >
                  {"10 napos"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oACsY
                  )}
                >
                  {"9630 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas7"}
                  data-plasmic-override={overrides.vasarlas7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas7)}
                >
                  <div
                    data-plasmic-name={"button7"}
                    data-plasmic-override={overrides.button7}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button7
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"haviMatricaFrame2"}
                data-plasmic-override={overrides.haviMatricaFrame2}
                className={classNames(projectcss.all, sty.haviMatricaFrame2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2I3Xw
                  )}
                >
                  {"Havi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cq2Iy
                  )}
                >
                  {"15170 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas8"}
                  data-plasmic-override={overrides.vasarlas8}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas8)}
                >
                  <div
                    data-plasmic-name={"button8"}
                    data-plasmic-override={overrides.button8}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button8
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"varmegyeiEvesMatricaFrame2"}
                data-plasmic-override={overrides.varmegyeiEvesMatricaFrame2}
                className={classNames(
                  projectcss.all,
                  sty.varmegyeiEvesMatricaFrame2
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4VgoX
                  )}
                >
                  {"V\u00e1rmegyei \u00e9ves"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__spwAs
                  )}
                >
                  {"13780 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas9"}
                  data-plasmic-override={overrides.vasarlas9}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas9)}
                >
                  <div
                    data-plasmic-name={"button9"}
                    data-plasmic-override={overrides.button9}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button9
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"evesMatricaFrame2"}
                data-plasmic-override={overrides.evesMatricaFrame2}
                className={classNames(projectcss.all, sty.evesMatricaFrame2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gbJrl
                  )}
                >
                  {"V\u00e1rmegyei \u00e9ves"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zf6
                  )}
                >
                  {"84040 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas10"}
                  data-plasmic-override={overrides.vasarlas10}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas10)}
                >
                  <div
                    data-plasmic-name={"button10"}
                    data-plasmic-override={overrides.button10}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button10
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"d212"}
                data-plasmic-override={overrides.d212}
                className={classNames(projectcss.all, sty.d212)}
              />

              <div
                data-plasmic-name={"d222"}
                data-plasmic-override={overrides.d222}
                className={classNames(projectcss.all, sty.d222)}
              />
            </div>
            <div
              data-plasmic-name={"d1MVasarlas"}
              data-plasmic-override={overrides.d1MVasarlas}
              className={classNames(projectcss.all, sty.d1MVasarlas)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wKmq
                )}
              >
                {"Kiz\u00e1r\u00f3lag motorker\u00e9kp\u00e1rokra."}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ecxT
                )}
              >
                {"D1M"}
              </div>
              <div
                data-plasmic-name={"napiMatricaFrame3"}
                data-plasmic-override={overrides.napiMatricaFrame3}
                className={classNames(projectcss.all, sty.napiMatricaFrame3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__heT8F
                  )}
                >
                  {"Napi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3DJaX
                  )}
                >
                  {"2660 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas11"}
                  data-plasmic-override={overrides.vasarlas11}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas11)}
                >
                  <div
                    data-plasmic-name={"button11"}
                    data-plasmic-override={overrides.button11}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button11
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"_10NaposMatricaFrame3"}
                data-plasmic-override={overrides._10NaposMatricaFrame3}
                className={classNames(
                  projectcss.all,
                  sty._10NaposMatricaFrame3
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ymfrL
                  )}
                >
                  {"10 napos"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pgSiC
                  )}
                >
                  {"3310 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas12"}
                  data-plasmic-override={overrides.vasarlas12}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas12)}
                >
                  <div
                    data-plasmic-name={"button12"}
                    data-plasmic-override={overrides.button12}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button12
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"haviMatricaFrame3"}
                data-plasmic-override={overrides.haviMatricaFrame3}
                className={classNames(projectcss.all, sty.haviMatricaFrame3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__no7Jf
                  )}
                >
                  {"Havi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ozavl
                  )}
                >
                  {"5360 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas13"}
                  data-plasmic-override={overrides.vasarlas13}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas13)}
                >
                  <div
                    data-plasmic-name={"button13"}
                    data-plasmic-override={overrides.button13}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button13
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"d1M2"}
                data-plasmic-override={overrides.d1M2}
                className={classNames(projectcss.all, sty.d1M2)}
              />
            </div>
            <div
              data-plasmic-name={"spacer"}
              data-plasmic-override={overrides.spacer}
              className={classNames(projectcss.all, sty.spacer)}
            />

            <div
              data-plasmic-name={"uVasarlas"}
              data-plasmic-override={overrides.uVasarlas}
              className={classNames(projectcss.all, sty.uVasarlas)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xQijU
                )}
              >
                {
                  "D2 \u00e9s B2 d\u00edjkateg\u00f3ri\u00e1ba tartoz\u00f3 j\u00e1rm\u0171vek vontatm\u00e1nya."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h8YLj
                )}
              >
                {"U"}
              </div>
              <div
                data-plasmic-name={"napiMatricaFrame4"}
                data-plasmic-override={overrides.napiMatricaFrame4}
                className={classNames(projectcss.all, sty.napiMatricaFrame4)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qztZ
                  )}
                >
                  {"Napi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xv6I4
                  )}
                >
                  {"5320 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas14"}
                  data-plasmic-override={overrides.vasarlas14}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas14)}
                >
                  <div
                    data-plasmic-name={"button14"}
                    data-plasmic-override={overrides.button14}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button14
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"_10NaposMatricaFrame4"}
                data-plasmic-override={overrides._10NaposMatricaFrame4}
                className={classNames(
                  projectcss.all,
                  sty._10NaposMatricaFrame4
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c0LfO
                  )}
                >
                  {"10 napos"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aN6VD
                  )}
                >
                  {"6620 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas15"}
                  data-plasmic-override={overrides.vasarlas15}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas15)}
                >
                  <div
                    data-plasmic-name={"button15"}
                    data-plasmic-override={overrides.button15}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button15
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"haviMatricaFrame4"}
                data-plasmic-override={overrides.haviMatricaFrame4}
                className={classNames(projectcss.all, sty.haviMatricaFrame4)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rbq9J
                  )}
                >
                  {"Havi"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kpuId
                  )}
                >
                  {"10710 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas16"}
                  data-plasmic-override={overrides.vasarlas16}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas16)}
                >
                  <div
                    data-plasmic-name={"button16"}
                    data-plasmic-override={overrides.button16}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button16
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"varmegyeiEvesMatricaFrame3"}
                data-plasmic-override={overrides.varmegyeiEvesMatricaFrame3}
                className={classNames(
                  projectcss.all,
                  sty.varmegyeiEvesMatricaFrame3
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v7Fn
                  )}
                >
                  {"V\u00e1rmegyei \u00e9ves"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__serA
                  )}
                >
                  {"6890 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas17"}
                  data-plasmic-override={overrides.vasarlas17}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas17)}
                >
                  <div
                    data-plasmic-name={"button17"}
                    data-plasmic-override={overrides.button17}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button17
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"evesMatricaFrame3"}
                data-plasmic-override={overrides.evesMatricaFrame3}
                className={classNames(projectcss.all, sty.evesMatricaFrame3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z1GMt
                  )}
                >
                  {"V\u00e1rmegyei \u00e9ves"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cVXpe
                  )}
                >
                  {"59210 Ft"}
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"vasarlas18"}
                  data-plasmic-override={overrides.vasarlas18}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.vasarlas18)}
                >
                  <div
                    data-plasmic-name={"button18"}
                    data-plasmic-override={overrides.button18}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button18
                    )}
                  >
                    {"V\u00e1s\u00e1rl\u00e1s"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"u2"}
                data-plasmic-override={overrides.u2}
                className={classNames(projectcss.all, sty.u2)}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__qeSpb)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__wbOix)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___37Bv)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2TXhE)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"40px"}
                    src={{
                      src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgY2xhc3M9Ikljb25fX0ltYWdlLXNjLTF0N2Z2azUtMCBjRlBLZkUiPgogIDxwYXRoIGZpbGw9IiMxNDE4MjQiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTMuMDA1IDNIMTV2MTJIMy4wMDVWM3pNMTQuNSAyMWE2LjUgNi41IDAgMTAwLTEzIDYuNSA2LjUgMCAwMDAgMTN6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==",
                      fullWidth: 150,
                      fullHeight: 150,
                      aspectRatio: 1
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__mApfm)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cZdHo
                      )}
                    >
                      {"Connect with us"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__mzwze)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___9P0Ol)}
                        role={"img"}
                      />

                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg__zWg6)}
                        role={"img"}
                      />

                      <Icon28Icon
                        className={classNames(projectcss.all, sty.svg__hofX)}
                        role={"img"}
                      />
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__e5CWf)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cShX)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g0ML
                    )}
                  >
                    {"Product"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ykqLt
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Pricing"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fyKZj
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Log in"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___0A1Il
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Integrations"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dcXvP
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Insights"}
                  </PlasmicLink__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__b9Ngp)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___7XxB)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ekyvv
                    )}
                  >
                    {"Support"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__vruIj
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Documentation"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__h04I
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"FAQs"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__cQwcs
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Status"}
                  </PlasmicLink__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__jSsy2)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iP1ZG)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xtRsG
                    )}
                  >
                    {"Company"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__d3Inb
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"About"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__pvRrE
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Contact us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___448Ic
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Careers"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___46Stb
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Media"}
                  </PlasmicLink__>
                </Stack__>
              </div>
            </Stack__>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "main",
    "virpayFejlec1",
    "d1Teaser",
    "d111",
    "d121",
    "uTeaser",
    "u1",
    "d2Teaser",
    "d211",
    "d221",
    "d1MTeaser",
    "d1M1",
    "d1Vasarlas",
    "d112",
    "d122",
    "napiMatricaFrame",
    "vasarlas",
    "button",
    "_10NaposMatricaFrame",
    "vasarlas2",
    "button2",
    "haviMatricaFrame",
    "vasarlas3",
    "button3",
    "varmegyeiEvesMatricaFrame",
    "vasarlas4",
    "button4",
    "evesMatricaFrame",
    "vasarlas5",
    "button5",
    "d2Vasarlas",
    "napiMatricaFrame2",
    "vasarlas6",
    "button6",
    "_10NaposMatricaFrame2",
    "vasarlas7",
    "button7",
    "haviMatricaFrame2",
    "vasarlas8",
    "button8",
    "varmegyeiEvesMatricaFrame2",
    "vasarlas9",
    "button9",
    "evesMatricaFrame2",
    "vasarlas10",
    "button10",
    "d212",
    "d222",
    "d1MVasarlas",
    "napiMatricaFrame3",
    "vasarlas11",
    "button11",
    "_10NaposMatricaFrame3",
    "vasarlas12",
    "button12",
    "haviMatricaFrame3",
    "vasarlas13",
    "button13",
    "d1M2",
    "spacer",
    "uVasarlas",
    "napiMatricaFrame4",
    "vasarlas14",
    "button14",
    "_10NaposMatricaFrame4",
    "vasarlas15",
    "button15",
    "haviMatricaFrame4",
    "vasarlas16",
    "button16",
    "varmegyeiEvesMatricaFrame3",
    "vasarlas17",
    "button17",
    "evesMatricaFrame3",
    "vasarlas18",
    "button18",
    "u2",
    "columns"
  ],
  main: [
    "main",
    "virpayFejlec1",
    "d1Teaser",
    "d111",
    "d121",
    "uTeaser",
    "u1",
    "d2Teaser",
    "d211",
    "d221",
    "d1MTeaser",
    "d1M1",
    "d1Vasarlas",
    "d112",
    "d122",
    "napiMatricaFrame",
    "vasarlas",
    "button",
    "_10NaposMatricaFrame",
    "vasarlas2",
    "button2",
    "haviMatricaFrame",
    "vasarlas3",
    "button3",
    "varmegyeiEvesMatricaFrame",
    "vasarlas4",
    "button4",
    "evesMatricaFrame",
    "vasarlas5",
    "button5",
    "d2Vasarlas",
    "napiMatricaFrame2",
    "vasarlas6",
    "button6",
    "_10NaposMatricaFrame2",
    "vasarlas7",
    "button7",
    "haviMatricaFrame2",
    "vasarlas8",
    "button8",
    "varmegyeiEvesMatricaFrame2",
    "vasarlas9",
    "button9",
    "evesMatricaFrame2",
    "vasarlas10",
    "button10",
    "d212",
    "d222",
    "d1MVasarlas",
    "napiMatricaFrame3",
    "vasarlas11",
    "button11",
    "_10NaposMatricaFrame3",
    "vasarlas12",
    "button12",
    "haviMatricaFrame3",
    "vasarlas13",
    "button13",
    "d1M2",
    "spacer",
    "uVasarlas",
    "napiMatricaFrame4",
    "vasarlas14",
    "button14",
    "_10NaposMatricaFrame4",
    "vasarlas15",
    "button15",
    "haviMatricaFrame4",
    "vasarlas16",
    "button16",
    "varmegyeiEvesMatricaFrame3",
    "vasarlas17",
    "button17",
    "evesMatricaFrame3",
    "vasarlas18",
    "button18",
    "u2"
  ],
  virpayFejlec1: ["virpayFejlec1"],
  d1Teaser: ["d1Teaser", "d111", "d121"],
  d111: ["d111"],
  d121: ["d121"],
  uTeaser: ["uTeaser", "u1"],
  u1: ["u1"],
  d2Teaser: ["d2Teaser", "d211", "d221"],
  d211: ["d211"],
  d221: ["d221"],
  d1MTeaser: ["d1MTeaser", "d1M1"],
  d1M1: ["d1M1"],
  d1Vasarlas: [
    "d1Vasarlas",
    "d112",
    "d122",
    "napiMatricaFrame",
    "vasarlas",
    "button",
    "_10NaposMatricaFrame",
    "vasarlas2",
    "button2",
    "haviMatricaFrame",
    "vasarlas3",
    "button3",
    "varmegyeiEvesMatricaFrame",
    "vasarlas4",
    "button4",
    "evesMatricaFrame",
    "vasarlas5",
    "button5"
  ],
  d112: ["d112"],
  d122: ["d122"],
  napiMatricaFrame: ["napiMatricaFrame", "vasarlas", "button"],
  vasarlas: ["vasarlas", "button"],
  button: ["button"],
  _10NaposMatricaFrame: ["_10NaposMatricaFrame", "vasarlas2", "button2"],
  vasarlas2: ["vasarlas2", "button2"],
  button2: ["button2"],
  haviMatricaFrame: ["haviMatricaFrame", "vasarlas3", "button3"],
  vasarlas3: ["vasarlas3", "button3"],
  button3: ["button3"],
  varmegyeiEvesMatricaFrame: [
    "varmegyeiEvesMatricaFrame",
    "vasarlas4",
    "button4"
  ],
  vasarlas4: ["vasarlas4", "button4"],
  button4: ["button4"],
  evesMatricaFrame: ["evesMatricaFrame", "vasarlas5", "button5"],
  vasarlas5: ["vasarlas5", "button5"],
  button5: ["button5"],
  d2Vasarlas: [
    "d2Vasarlas",
    "napiMatricaFrame2",
    "vasarlas6",
    "button6",
    "_10NaposMatricaFrame2",
    "vasarlas7",
    "button7",
    "haviMatricaFrame2",
    "vasarlas8",
    "button8",
    "varmegyeiEvesMatricaFrame2",
    "vasarlas9",
    "button9",
    "evesMatricaFrame2",
    "vasarlas10",
    "button10",
    "d212",
    "d222"
  ],
  napiMatricaFrame2: ["napiMatricaFrame2", "vasarlas6", "button6"],
  vasarlas6: ["vasarlas6", "button6"],
  button6: ["button6"],
  _10NaposMatricaFrame2: ["_10NaposMatricaFrame2", "vasarlas7", "button7"],
  vasarlas7: ["vasarlas7", "button7"],
  button7: ["button7"],
  haviMatricaFrame2: ["haviMatricaFrame2", "vasarlas8", "button8"],
  vasarlas8: ["vasarlas8", "button8"],
  button8: ["button8"],
  varmegyeiEvesMatricaFrame2: [
    "varmegyeiEvesMatricaFrame2",
    "vasarlas9",
    "button9"
  ],
  vasarlas9: ["vasarlas9", "button9"],
  button9: ["button9"],
  evesMatricaFrame2: ["evesMatricaFrame2", "vasarlas10", "button10"],
  vasarlas10: ["vasarlas10", "button10"],
  button10: ["button10"],
  d212: ["d212"],
  d222: ["d222"],
  d1MVasarlas: [
    "d1MVasarlas",
    "napiMatricaFrame3",
    "vasarlas11",
    "button11",
    "_10NaposMatricaFrame3",
    "vasarlas12",
    "button12",
    "haviMatricaFrame3",
    "vasarlas13",
    "button13",
    "d1M2"
  ],
  napiMatricaFrame3: ["napiMatricaFrame3", "vasarlas11", "button11"],
  vasarlas11: ["vasarlas11", "button11"],
  button11: ["button11"],
  _10NaposMatricaFrame3: ["_10NaposMatricaFrame3", "vasarlas12", "button12"],
  vasarlas12: ["vasarlas12", "button12"],
  button12: ["button12"],
  haviMatricaFrame3: ["haviMatricaFrame3", "vasarlas13", "button13"],
  vasarlas13: ["vasarlas13", "button13"],
  button13: ["button13"],
  d1M2: ["d1M2"],
  spacer: ["spacer"],
  uVasarlas: [
    "uVasarlas",
    "napiMatricaFrame4",
    "vasarlas14",
    "button14",
    "_10NaposMatricaFrame4",
    "vasarlas15",
    "button15",
    "haviMatricaFrame4",
    "vasarlas16",
    "button16",
    "varmegyeiEvesMatricaFrame3",
    "vasarlas17",
    "button17",
    "evesMatricaFrame3",
    "vasarlas18",
    "button18",
    "u2"
  ],
  napiMatricaFrame4: ["napiMatricaFrame4", "vasarlas14", "button14"],
  vasarlas14: ["vasarlas14", "button14"],
  button14: ["button14"],
  _10NaposMatricaFrame4: ["_10NaposMatricaFrame4", "vasarlas15", "button15"],
  vasarlas15: ["vasarlas15", "button15"],
  button15: ["button15"],
  haviMatricaFrame4: ["haviMatricaFrame4", "vasarlas16", "button16"],
  vasarlas16: ["vasarlas16", "button16"],
  button16: ["button16"],
  varmegyeiEvesMatricaFrame3: [
    "varmegyeiEvesMatricaFrame3",
    "vasarlas17",
    "button17"
  ],
  vasarlas17: ["vasarlas17", "button17"],
  button17: ["button17"],
  evesMatricaFrame3: ["evesMatricaFrame3", "vasarlas18", "button18"],
  vasarlas18: ["vasarlas18", "button18"],
  button18: ["button18"],
  u2: ["u2"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  main: "div";
  virpayFejlec1: "div";
  d1Teaser: "div";
  d111: "div";
  d121: "div";
  uTeaser: "div";
  u1: "div";
  d2Teaser: "div";
  d211: "div";
  d221: "div";
  d1MTeaser: "div";
  d1M1: "div";
  d1Vasarlas: "div";
  d112: "div";
  d122: "div";
  napiMatricaFrame: "div";
  vasarlas: "div";
  button: "div";
  _10NaposMatricaFrame: "div";
  vasarlas2: "div";
  button2: "div";
  haviMatricaFrame: "div";
  vasarlas3: "div";
  button3: "div";
  varmegyeiEvesMatricaFrame: "div";
  vasarlas4: "div";
  button4: "div";
  evesMatricaFrame: "div";
  vasarlas5: "div";
  button5: "div";
  d2Vasarlas: "div";
  napiMatricaFrame2: "div";
  vasarlas6: "div";
  button6: "div";
  _10NaposMatricaFrame2: "div";
  vasarlas7: "div";
  button7: "div";
  haviMatricaFrame2: "div";
  vasarlas8: "div";
  button8: "div";
  varmegyeiEvesMatricaFrame2: "div";
  vasarlas9: "div";
  button9: "div";
  evesMatricaFrame2: "div";
  vasarlas10: "div";
  button10: "div";
  d212: "div";
  d222: "div";
  d1MVasarlas: "div";
  napiMatricaFrame3: "div";
  vasarlas11: "div";
  button11: "div";
  _10NaposMatricaFrame3: "div";
  vasarlas12: "div";
  button12: "div";
  haviMatricaFrame3: "div";
  vasarlas13: "div";
  button13: "div";
  d1M2: "div";
  spacer: "div";
  uVasarlas: "div";
  napiMatricaFrame4: "div";
  vasarlas14: "div";
  button14: "div";
  _10NaposMatricaFrame4: "div";
  vasarlas15: "div";
  button15: "div";
  haviMatricaFrame4: "div";
  vasarlas16: "div";
  button16: "div";
  varmegyeiEvesMatricaFrame3: "div";
  vasarlas17: "div";
  button17: "div";
  evesMatricaFrame3: "div";
  vasarlas18: "div";
  button18: "div";
  u2: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    main: makeNodeComponent("main"),
    virpayFejlec1: makeNodeComponent("virpayFejlec1"),
    d1Teaser: makeNodeComponent("d1Teaser"),
    d111: makeNodeComponent("d111"),
    d121: makeNodeComponent("d121"),
    uTeaser: makeNodeComponent("uTeaser"),
    u1: makeNodeComponent("u1"),
    d2Teaser: makeNodeComponent("d2Teaser"),
    d211: makeNodeComponent("d211"),
    d221: makeNodeComponent("d221"),
    d1MTeaser: makeNodeComponent("d1MTeaser"),
    d1M1: makeNodeComponent("d1M1"),
    d1Vasarlas: makeNodeComponent("d1Vasarlas"),
    d112: makeNodeComponent("d112"),
    d122: makeNodeComponent("d122"),
    napiMatricaFrame: makeNodeComponent("napiMatricaFrame"),
    vasarlas: makeNodeComponent("vasarlas"),
    button: makeNodeComponent("button"),
    _10NaposMatricaFrame: makeNodeComponent("_10NaposMatricaFrame"),
    vasarlas2: makeNodeComponent("vasarlas2"),
    button2: makeNodeComponent("button2"),
    haviMatricaFrame: makeNodeComponent("haviMatricaFrame"),
    vasarlas3: makeNodeComponent("vasarlas3"),
    button3: makeNodeComponent("button3"),
    varmegyeiEvesMatricaFrame: makeNodeComponent("varmegyeiEvesMatricaFrame"),
    vasarlas4: makeNodeComponent("vasarlas4"),
    button4: makeNodeComponent("button4"),
    evesMatricaFrame: makeNodeComponent("evesMatricaFrame"),
    vasarlas5: makeNodeComponent("vasarlas5"),
    button5: makeNodeComponent("button5"),
    d2Vasarlas: makeNodeComponent("d2Vasarlas"),
    napiMatricaFrame2: makeNodeComponent("napiMatricaFrame2"),
    vasarlas6: makeNodeComponent("vasarlas6"),
    button6: makeNodeComponent("button6"),
    _10NaposMatricaFrame2: makeNodeComponent("_10NaposMatricaFrame2"),
    vasarlas7: makeNodeComponent("vasarlas7"),
    button7: makeNodeComponent("button7"),
    haviMatricaFrame2: makeNodeComponent("haviMatricaFrame2"),
    vasarlas8: makeNodeComponent("vasarlas8"),
    button8: makeNodeComponent("button8"),
    varmegyeiEvesMatricaFrame2: makeNodeComponent("varmegyeiEvesMatricaFrame2"),
    vasarlas9: makeNodeComponent("vasarlas9"),
    button9: makeNodeComponent("button9"),
    evesMatricaFrame2: makeNodeComponent("evesMatricaFrame2"),
    vasarlas10: makeNodeComponent("vasarlas10"),
    button10: makeNodeComponent("button10"),
    d212: makeNodeComponent("d212"),
    d222: makeNodeComponent("d222"),
    d1MVasarlas: makeNodeComponent("d1MVasarlas"),
    napiMatricaFrame3: makeNodeComponent("napiMatricaFrame3"),
    vasarlas11: makeNodeComponent("vasarlas11"),
    button11: makeNodeComponent("button11"),
    _10NaposMatricaFrame3: makeNodeComponent("_10NaposMatricaFrame3"),
    vasarlas12: makeNodeComponent("vasarlas12"),
    button12: makeNodeComponent("button12"),
    haviMatricaFrame3: makeNodeComponent("haviMatricaFrame3"),
    vasarlas13: makeNodeComponent("vasarlas13"),
    button13: makeNodeComponent("button13"),
    d1M2: makeNodeComponent("d1M2"),
    spacer: makeNodeComponent("spacer"),
    uVasarlas: makeNodeComponent("uVasarlas"),
    napiMatricaFrame4: makeNodeComponent("napiMatricaFrame4"),
    vasarlas14: makeNodeComponent("vasarlas14"),
    button14: makeNodeComponent("button14"),
    _10NaposMatricaFrame4: makeNodeComponent("_10NaposMatricaFrame4"),
    vasarlas15: makeNodeComponent("vasarlas15"),
    button15: makeNodeComponent("button15"),
    haviMatricaFrame4: makeNodeComponent("haviMatricaFrame4"),
    vasarlas16: makeNodeComponent("vasarlas16"),
    button16: makeNodeComponent("button16"),
    varmegyeiEvesMatricaFrame3: makeNodeComponent("varmegyeiEvesMatricaFrame3"),
    vasarlas17: makeNodeComponent("vasarlas17"),
    button17: makeNodeComponent("button17"),
    evesMatricaFrame3: makeNodeComponent("evesMatricaFrame3"),
    vasarlas18: makeNodeComponent("vasarlas18"),
    button18: makeNodeComponent("button18"),
    u2: makeNodeComponent("u2"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
