/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3tfavHgZw46Q2spXSS6bmf
// Component: 1zeuGDPa2dmH

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 3tfavHgZw46Q2spXSS6bmf/projectcss
import sty from "./PlasmicLogin.module.css"; // plasmic-import: 1zeuGDPa2dmH/css

createPlasmicElementProxy;

export type PlasmicLogin__VariantMembers = {};
export type PlasmicLogin__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogin__VariantsArgs;
export const PlasmicLogin__VariantProps = new Array<VariantPropType>();

export type PlasmicLogin__ArgsType = {};
type ArgPropType = keyof PlasmicLogin__ArgsType;
export const PlasmicLogin__ArgProps = new Array<ArgPropType>();

export type PlasmicLogin__OverridesType = {
  login?: Flex__<"div">;
  login2?: Flex__<"div">;
  signIn?: Flex__<"div">;
  button?: Flex__<"div">;
  jelszo?: Flex__<"div">;
  sampleText?: Flex__<"div">;
  email?: Flex__<"div">;
  sampleText2?: Flex__<"div">;
  _switch?: Flex__<"div">;
  handle?: Flex__<"div">;
  target?: Flex__<"div">;
  stateLayer?: Flex__<"div">;
  handleShape?: Flex__<"div">;
  container?: Flex__<"div">;
};

export interface DefaultLoginProps {
  className?: string;
}

const $$ = {};

function PlasmicLogin__RenderFunc(props: {
  variants: PlasmicLogin__VariantsArgs;
  args: PlasmicLogin__ArgsType;
  overrides: PlasmicLogin__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"login"}
          data-plasmic-override={overrides.login}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.login
          )}
        >
          <div
            data-plasmic-name={"login2"}
            data-plasmic-override={overrides.login2}
            className={classNames(projectcss.all, sty.login2)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"signIn"}
              data-plasmic-override={overrides.signIn}
              hasGap={true}
              className={classNames(projectcss.all, sty.signIn)}
            >
              <div
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.button
                )}
              >
                {"Bel\u00e9p\u00e9s"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"jelszo"}
              data-plasmic-override={overrides.jelszo}
              hasGap={true}
              className={classNames(projectcss.all, sty.jelszo)}
            >
              <div
                data-plasmic-name={"sampleText"}
                data-plasmic-override={overrides.sampleText}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.sampleText
                )}
              >
                {"Jelsz\u00f3"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"email"}
              data-plasmic-override={overrides.email}
              hasGap={true}
              className={classNames(projectcss.all, sty.email)}
            >
              <div
                data-plasmic-name={"sampleText2"}
                data-plasmic-override={overrides.sampleText2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.sampleText2
                )}
              >
                {"Email c\u00edm"}
              </div>
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__svDrc
              )}
            >
              {"Bel\u00e9p\u00e9s"}
            </div>
            <div
              data-plasmic-name={"_switch"}
              data-plasmic-override={overrides._switch}
              className={classNames(projectcss.all, sty._switch)}
            >
              <div
                data-plasmic-name={"handle"}
                data-plasmic-override={overrides.handle}
                className={classNames(projectcss.all, sty.handle)}
              >
                <div
                  data-plasmic-name={"target"}
                  data-plasmic-override={overrides.target}
                  className={classNames(projectcss.all, sty.target)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"stateLayer"}
                    data-plasmic-override={overrides.stateLayer}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.stateLayer)}
                  >
                    <div
                      data-plasmic-name={"handleShape"}
                      data-plasmic-override={overrides.handleShape}
                      className={classNames(projectcss.all, sty.handleShape)}
                    >
                      <div
                        data-plasmic-name={"container"}
                        data-plasmic-override={overrides.container}
                        className={classNames(projectcss.all, sty.container)}
                      />
                    </div>
                  </Stack__>
                </div>
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__p4I4N
              )}
            >
              {"Eml\u00e9kezz r\u00e1m"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kpi46
              )}
            >
              {"Elfelejtettem a jelszavam"}
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__bFrCc)}
              displayHeight={"28px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"28px"}
              loading={"lazy"}
              src={{
                src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyOCAyOCI+CiAgPGcgY2xpcC1wYXRoPSJ1cmwoI2xwQUZ6MW1Id1JGYmEpIiBzdHJva2U9IiMxRTFFMUUiIHN0cm9rZS13aWR0aD0iNCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj4KICAgIDxwYXRoIGQ9Ik0xLjE2NyAxNFM1LjgzMyA0LjY2NyAxNCA0LjY2NyAyNi44MzMgMTQgMjYuODMzIDE0IDIyLjE2NyAyMy4zMzMgMTQgMjMuMzMzIDEuMTY3IDE0IDEuMTY3IDE0eiIvPgogICAgPHBhdGggZD0iTTE0IDE3LjVhMy41IDMuNSAwIDEwMC03IDMuNSAzLjUgMCAwMDAgN3oiLz4KICA8L2c+CiAgPGRlZnM+CiAgICA8Y2xpcFBhdGggaWQ9ImxwQUZ6MW1Id1JGYmEiPgogICAgICA8cGF0aCBmaWxsPSIjZmZmIiBkPSJNMCAwaDI4djI4SDB6Ii8+CiAgICA8L2NsaXBQYXRoPgogIDwvZGVmcz4KPC9zdmc+Cg==",
                fullWidth: 28,
                fullHeight: 28,
                aspectRatio: 1
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__qTjoq)}
              displayHeight={"28px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"28px"}
              loading={"lazy"}
              src={{
                src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyOCAyOCI+CiAgPGcgY2xpcC1wYXRoPSJ1cmwoI1U5LXhWMUQ3LXpXMmEpIj4KICAgIDxwYXRoIGQ9Ik0yMC45MyAyMC45M0ExMS43NDggMTEuNzQ4IDAgMDExNCAyMy4zMzNDNS44MzMgMjMuMzMzIDEuMTY3IDE0IDEuMTY3IDE0QTIxLjUyNCAyMS41MjQgMCAwMTcuMDcgNy4wN200LjQ4LTIuMTIzYTEwLjY0IDEwLjY0IDAgMDEyLjQ1LS4yOEMyMi4xNjcgNC42NjcgMjYuODMzIDE0IDI2LjgzMyAxNGEyMS41OCAyMS41OCAwIDAxLTIuNTIgMy43MjJtLTcuODQtMS4yNDlhMy41IDMuNSAwIDExLTQuOTQ2LTQuOTQ2TTEuMTY3IDEuMTY3bDI1LjY2NiAyNS42NjYiIHN0cm9rZT0iIzFFMUUxRSIgc3Ryb2tlLXdpZHRoPSI0IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiLz4KICA8L2c+CiAgPGRlZnM+CiAgICA8Y2xpcFBhdGggaWQ9IlU5LXhWMUQ3LXpXMmEiPgogICAgICA8cGF0aCBmaWxsPSIjZmZmIiBkPSJNMCAwaDI4djI4SDB6Ii8+CiAgICA8L2NsaXBQYXRoPgogIDwvZGVmcz4KPC9zdmc+Cg==",
                fullWidth: 28,
                fullHeight: 28,
                aspectRatio: 1
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__y2Iqc
              )}
            >
              {"M\u00e9g nem regisztr\u00e1lt?"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cdVyx
              )}
            >
              {"Regisztr\u00e1ljon most!"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  login: [
    "login",
    "login2",
    "signIn",
    "button",
    "jelszo",
    "sampleText",
    "email",
    "sampleText2",
    "_switch",
    "handle",
    "target",
    "stateLayer",
    "handleShape",
    "container"
  ],
  login2: [
    "login2",
    "signIn",
    "button",
    "jelszo",
    "sampleText",
    "email",
    "sampleText2",
    "_switch",
    "handle",
    "target",
    "stateLayer",
    "handleShape",
    "container"
  ],
  signIn: ["signIn", "button"],
  button: ["button"],
  jelszo: ["jelszo", "sampleText"],
  sampleText: ["sampleText"],
  email: ["email", "sampleText2"],
  sampleText2: ["sampleText2"],
  _switch: [
    "_switch",
    "handle",
    "target",
    "stateLayer",
    "handleShape",
    "container"
  ],
  handle: ["handle", "target", "stateLayer", "handleShape", "container"],
  target: ["target", "stateLayer", "handleShape", "container"],
  stateLayer: ["stateLayer", "handleShape", "container"],
  handleShape: ["handleShape", "container"],
  container: ["container"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  login: "div";
  login2: "div";
  signIn: "div";
  button: "div";
  jelszo: "div";
  sampleText: "div";
  email: "div";
  sampleText2: "div";
  _switch: "div";
  handle: "div";
  target: "div";
  stateLayer: "div";
  handleShape: "div";
  container: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogin__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogin__VariantsArgs;
    args?: PlasmicLogin__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLogin__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLogin__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogin__ArgProps,
          internalVariantPropNames: PlasmicLogin__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogin__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "login") {
    func.displayName = "PlasmicLogin";
  } else {
    func.displayName = `PlasmicLogin.${nodeName}`;
  }
  return func;
}

export const PlasmicLogin = Object.assign(
  // Top-level PlasmicLogin renders the root element
  makeNodeComponent("login"),
  {
    // Helper components rendering sub-elements
    login2: makeNodeComponent("login2"),
    signIn: makeNodeComponent("signIn"),
    button: makeNodeComponent("button"),
    jelszo: makeNodeComponent("jelszo"),
    sampleText: makeNodeComponent("sampleText"),
    email: makeNodeComponent("email"),
    sampleText2: makeNodeComponent("sampleText2"),
    _switch: makeNodeComponent("_switch"),
    handle: makeNodeComponent("handle"),
    target: makeNodeComponent("target"),
    stateLayer: makeNodeComponent("stateLayer"),
    handleShape: makeNodeComponent("handleShape"),
    container: makeNodeComponent("container"),

    // Metadata about props expected for PlasmicLogin
    internalVariantProps: PlasmicLogin__VariantProps,
    internalArgProps: PlasmicLogin__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLogin;
/* prettier-ignore-end */
